flash: edit

diff --git a/recipes-images/base-files/base-files/flash b/recipes-images/base-files/base-files/flash
--- a/recipes-images/base-files/base-files/flash
+++ b/recipes-images/base-files/base-files/flash
@@ -7,6 +7,8 @@ image="neutrino-image_flash.zip"
 imagesource="$url/$image"
 hdd_mount="/media/USB"
 mountpoint -q /media/HDD && hdd_mount="/media/HDD"
+imagebase="$hdd_mount/service/image"
+imageversion_online="$url/imageversion"
 kernelname="kernel.bin"
 devbase="/dev/mmcblk0p"
 dev_display="/dev/dbox/oled0"
@@ -67,66 +69,70 @@ else
 	fi
 fi
 
+imageversion_local="$imagebase/imageversion_partition_$part"
 partition_sectorsize="$(gdisk -l $devbase$root | grep 'Total free space' | awk '{print $5}')"
 [ $partition_sectorsize -ne 1638333 ] && printf '\n\033[31m%s\n' "The partition scheme is invalid ... use ofgwrite for flashing" && exit 2;
 
 reset
 
-if [ -z $2 ] && [ $1 != "--restore" ] || [ $2 = "--force" ]; then
-	imagebase="$hdd_mount/service/image"
-	imagedir="$imagebase/$machine"
-	imagefile="$imagebase/$image"
-	imageversion="$imagedir/imageversion"
-	imageversion_local="$imagebase/imageversion_partition_$part"
-	imageversion_online="$url/imageversion"
-	[ ! -d $imagebase ] && mkdir -p $imagebase
-	space_available="$(df -Pk $imagebase | awk 'NR==2 {print $4}')"
-	[ $space_available -lt 1048576 ] && printf '\n\033[31m%s\n' "You need at least 1G of free space on $hdd_mount" && exit 3;
-	if [ -z $2 ]; then
-        	[ ! -f $imageversion_local ] && touch $imageversion_local
-		md5_imageversion_online=$(curl -s $imageversion_online | md5sum | awk '{print $1}')
-		md5_imageversion_local=$(md5sum "$imageversion_local" | awk '{print $1}')
-		[ $md5_imageversion_online = $md5_imageversion_local ] && printf '\n\033[32m%s\n' "No update available" && \
-		echo "No update available" > $dev_display && exit 4;
-	else
-                printf '\033[31m'
-	fi
-	echo "Downloading $image" > $dev_display
-	printf '\n\033[1m%s\n\033[0m' "Downloading $imagesource"
-	unpack="unzip -x $imagefile -d $imagebase"
-	curl $imagesource -o $imagefile || { printf '\n\033[31m%s\n' "Downloading the image failed" ; exit 5; }
-	[ -d $imagedir ] && rm -r $imagedir
-	echo "Decompressing $image" > $dev_display
-        printf '\n\033[1m%s\n\033[0m' "Decompressing  $image"
-	$unpack || { printf '\n\033[31m%s\n' "Unpacking the image failed" ; exit 6; }
-	cp -rf $imageversion $imageversion_local
-	[ -f $imagefile ] && rm $imagefile
-else
-	if [ $1 = "--restore" ]; then
-		imagedir="$hdd_mount/service/image/backup/$machine"
-	elif [[ $1 =~ ^[1-4]+$ ]]; then	
-		imagedir="$2"
-	fi
-	[ ! -f $imagedir/$imagename ] && printf '\n%s\n' "$imagedir/$imagename not found" && exit 1;
-	[ ! -f $imagedir/$kernelname ] && printf '\n%s\n' "$imagedir/$kernelname not found" && exit 1;
-	space_available="$(df -Pk $imagedir | awk 'NR==2 {print $4}')"
-	[ $space_available -lt 1048576 ] && printf '\n\033[31m%s\n' "You need at least 1G of free space on your device" && exit 1;
-fi
-
+function write_image () {
 [ $rootdevice = $devbase$root ] && stop_services
-
 printf '\n\033[1m%s\n\033[0m' "Writing image into partition $part"
 echo "Writing image into partition $part" > $dev_display
-
 printf '\033[33m%s\033[37m%s\n' "Writing kernel into $devbase$kernel"
-pv < $imagedir/$kernelname > $devbase$kernel \
-|| { printf '\033[31m%s\n' "Writing the kernel failed" ; exit 7; }
-
+pv < $imagedir/$kernelname > $devbase$kernel || { printf '\033[31m%s\n' "Writing the kernel failed" ; exit 7; }
 printf '\033[33m%s\033[37m%s\n' "Writing rootfs into $devbase$root"
-bzip2 -cd $imagedir/$imagename | pv > $devbase$root \
-|| { printf '\033[31m%s\n' "Writing rootfs into $devbase$root failed" ; exit 8; }
+bzip2 -cd $imagedir/$imagename | pv > $devbase$root || { printf '\033[31m%s\n' "Writing rootfs into $devbase$root failed" ; exit 8; }
 printf '\n\033[1m\033[32m%s\033[0m\n' "Flash successful"
-
-[ $rootdevice = $devbase$root ] && echo "...Reboot" > $dev_display && \
-reboot="$(echo 1 > /proc/sys/kernel/sysrq && echo b > /proc/sysrq-trigger)"
+[ $rootdevice = $devbase$root ] && echo "...Reboot" > $dev_display && reboot="$(echo 1 > /proc/sys/kernel/sysrq && echo b > /proc/sysrq-trigger)"
 echo "Flash succeeded" > $dev_display
+}
+
+if [ -z $2 ] || [ $2 = "--force" ]; then
+	case $1 in
+	1|4)
+		imagedir="$imagebase/$machine"
+		imagefile="$imagebase/$image"
+		imageversion="$imagedir/imageversion"
+		[ ! -d $imagebase ] && mkdir -p $imagebase
+		space_available="$(df -Pk $imagebase | awk 'NR==2 {print $4}')"
+		[ $space_available -lt 1048576 ] && printf '\n\033[31m%s\n' "You need at least 1G of free space on $hdd_mount" && exit 3;
+		if [ -z $2 ]; then
+        		[ ! -f $imageversion_local ] && touch $imageversion_local
+			md5_imageversion_online=$(curl -s $imageversion_online | md5sum | awk '{print $1}')
+			md5_imageversion_local=$(md5sum "$imageversion_local" | awk '{print $1}')
+			[ $md5_imageversion_online = $md5_imageversion_local ] && printf '\n\033[32m%s\n' "No update available" && \
+			echo "No update available" > $dev_display && exit 4;
+		else
+                	printf '\033[31m'
+		fi
+		echo "Downloading $image" > $dev_display
+		printf '\n\033[1m%s\n\033[0m' "Downloading $imagesource"
+		unpack="unzip -x $imagefile -d $imagebase"
+		curl $imagesource -o $imagefile || { printf '\n\033[31m%s\n' "Downloading the image failed" ; exit 5; }
+		[ -d $imagedir ] && rm -r $imagedir
+		echo "Decompressing $image" > $dev_display
+        	printf '\n\033[1m%s\n\033[0m' "Decompressing  $image"
+		$unpack || { printf '\n\033[31m%s\n' "Unpacking the image failed" ; exit 6; }
+		cp -rf $imageversion $imageversion_local
+		[ -f $imagefile ] && rm $imagefile
+		write_image
+        	exit 0
+		;;
+	esac
+fi
+
+if [ $1 = "--restore" ]; then
+	imagedir="$hdd_mount/service/image/backup/$machine"
+elif [[ $1 =~ ^[1-4]+$ ]]; then	
+	imagedir="$2"
+fi
+imageversion="$imagedir/imageversion"
+cp -rf $imageversion $imageversion_local
+[ ! -f $imagedir/$imagename ] && printf '\n%s\n' "$imagedir/$imagename not found" && exit 1;
+[ ! -f $imagedir/$kernelname ] && printf '\n%s\n' "$imagedir/$kernelname not found" && exit 1;
+space_available="$(df -Pk $imagedir | awk 'NR==2 {print $4}')"
+[ $space_available -lt 1048576 ] && printf '\n\033[31m%s\n' "You need at least 1G of free space on your device" && exit 1;
+
+write_image
+exit 0 ;
