flash: avoid unneeded if cases; compatibility for busybox dd

diff --git a/recipes-images/base-files/base-files/flash b/recipes-images/base-files/base-files/flash
--- a/recipes-images/base-files/base-files/flash
+++ b/recipes-images/base-files/base-files/flash
@@ -6,17 +6,14 @@ imagefile="$imagebase/hd51.zip"
 imagename="neutrino-image-hd51.ext4.bz2"
 devbase="/dev/mmcblk0p"
 
-if  [ -z $1 ] || [ $1 = "-h" ] || [ $1 = "--help" ]; then
-        printf '\n%s\n' "Give the destination partition number [1 - 4] as first argument.
+[ -z $1 ] || [ $1 = "-h" ] || [ $1 = "--help" ] && printf '\n%s\n' "Give the destination partition number [1 - 4] as first argument.
 
 As second argument you can specify the path where the image is stored.
 If no second argument is given the image will be downloaded from
 
 $imagesource
 
-";
-	exit 0;
-fi
+" && exit 0;
 
 if [[ $1 =~ ^[0-9]+$ ]]; then
         if  [ $1 -lt 1 ] || [ $1 -gt 4 ]; then
@@ -45,9 +42,7 @@ fi
 rootdevice="$(sed -e 's/^.*root=//' -e 's/ .*$//' < /proc/cmdline)"
 partition_sectorsize="$(gdisk -l $devbase$root | grep 'Total free space' | awk '{print $5}')"
 
-if [ $partition_sectorsize -ne 1638333 ]; then
-        printf '\n%s\n' "The partition scheme is invalid ... use ofgwrite for flashing" ; exit 1;
-fi
+[ $partition_sectorsize -ne 1638333 ] && printf '\n%s\n' "The partition scheme is invalid ... use ofgwrite for flashing" && exit 1;
 
 reset
 
@@ -56,9 +51,7 @@ if [ -z $2 ]; then
 	unpack="unzip -x $imagefile -d $imagebase"
 	[ ! -d $imagebase ] && mkdir -p $imagebase
 	space_available="$(df -Pk $imagebase | awk 'NR==2 {print $4}')"
-	if [ $space_available -lt 1048576 ];then
-		printf '\n%s\n' "You need at least 1G of free space on your HDD" ; exit 1;
-	fi
+	[ $space_available -lt 1048576 ] && printf '\n%s\n' "You need at least 1G of free space on your HDD" && exit 1;
 	curl $imagesource -o $imagefile || { printf '\n%s\n' "Downloading the image failed" ; exit 1; }
 	printf '\n%s\n'
 	[ -d $imagedir ] && rm -r $imagedir
@@ -66,15 +59,10 @@ if [ -z $2 ]; then
 	[ -f $imagefile ] && rm $imagefile
 else
 	imagedir="$2"
-	if [ ! -f $imagedir/$imagename ]; then
-		printf '\n%s\n' "$2/$imagename not found" ; exit 1;
-	elif [ ! -f $imagedir/kernel.bin ]; then
-		printf '\n%s\n' "$2/kernel.bin not found" ; exit 1;
-	fi
+	[ ! -f $imagedir/$imagename ] && printf '\n%s\n' "$2/$imagename not found" && exit 1;
+	[ ! -f $imagedir/kernel.bin ] && printf '\n%s\n' "$2/kernel.bin not found" && exit 1;
 	space_available="$(df -Pk $imagedir | awk 'NR==2 {print $4}')"
-	if [ $space_available -lt 1048576 ];then
-		printf '\n%s\n' "You need at least 1G of free space on your device" ; exit 1;
-	fi
+	[ $space_available -lt 1048576 ] && printf '\n%s\n' "You need at least 1G of free space on your device" && exit 1;
 fi
 
 printf '\n%s\n' "Writing kernel into $devbase$kernel"
@@ -82,9 +70,9 @@ dd if=$imagedir/kernel.bin of=$devbase$kernel bs=1M status=progress conv=fsync \
 || { printf '\n%s\n' "Writing the kernel failed" ; exit 1; }
 
 printf '\n%s\n' "Writing rootfs into $devbase$root"
-bzip2 -cd $imagedir/$imagename | dd of=$devbase$root bs=1M status=progress conv=fsync \
+[ -f /bin/dd.coreutils ] && have_coreutils="status=progress"
+bzip2 -cd $imagedir/$imagename | dd of=$devbase$root bs=1M $have_coreutils conv=fsync \
 || { printf '\n%s\n' "Writing rootfs into $devbase$root failed" ; exit 1; }
 printf '\n%s\n' "Flash successful"
-if [ $rootdevice = $devbase$root ]; then
-	reboot="$(echo 1 > /proc/sys/kernel/sysrq && echo b > /proc/sysrq-trigger)"
-fi
+[ $rootdevice = $devbase$root ] && reboot="$(echo 1 > /proc/sys/kernel/sysrq && echo b > /proc/sysrq-trigger)"
+
