flash: cleanup

diff --git a/recipes-images/base-files/base-files/flash b/recipes-images/base-files/base-files/flash
--- a/recipes-images/base-files/base-files/flash
+++ b/recipes-images/base-files/base-files/flash
@@ -35,6 +35,14 @@ function stop_services () {
         pidof neutrino >> /dev/null && killall -9 neutrino
 }
 
+exit_done() {
+	sleep 3
+	clear
+	[ $rootdevice = $devbase$root ] && echo "...Reboot" > $dev_display && systemctl --force --force reboot
+	exit 0;
+}
+
+
 [[ $* = "-h" ]] || [[ $* = "--help" ]] && printf '\n\033[31m%s\n' "Give the destination partition number [1 - 4] as first argument.
 
 As second argument you can specify the path where the image is stored.
@@ -81,28 +89,24 @@ clear
 
 function write_image () {
 [[ $rootdevice = $devbase$root ]] && stop_services
+
 printf '\n\033[1m%s\n\033[0m' "Writing image into partition $part"
 echo "Writing image into partition $part" > $dev_display
-printf '\033[33m%s\033[37m%s\n' "Writing kernel into $devbase$kernel"
-pv < $imagedir/$kernelname > $devbase$kernel || { printf '\033[31m%s\n' "Writing the kernel failed" ; sleep 3; clear; exit 7; }
-printf '\033[33m%s\033[37m%s\n' "Writing rootfs into $devbase$root"
 
+printf '\033[33m%s\033[37m%s\n' "Writing kernel into $devbase$kernel"
+pv < $imagedir/$kernelname > $devbase$kernel
+
+printf '\033[33m%s\033[37m%s\n' "Writing rootfs into $devbase$root"
 if systemctl is-active restore@$part | grep "inactive" >> /dev/null; then
        echo $* | grep "restore" >> /dev/null && fsarchiver restfs -o -j2 -v -a $imagedir/$image_dec.fsa id=0,dest=$devbase$root
        echo $* | grep "restore" >> /dev/null || bzip2 -cd $imagedir/$imagename | pv > $devbase$root
 else
 	fsarchiver restfs -o -j2 -v -a $imagedir/$image_dec.fsa id=0,dest=$devbase$root
 fi
-
-printf '\n\033[1m\033[32m%s\033[0m\n' "Flash successful"
-printf '\033[1m\033[0m'
-[ $rootdevice = $devbase$root ] && echo "...Reboot" > $dev_display && systemctl --force reboot
+printf '\n\033[1m\033[32m%s\033[0m\n' "Flash successful"; printf '\033[1m\033[0m'
 echo "Flash succeeded" > $dev_display
-sleep 3
-clear
-exit 0;
+exit_done
 }
-
 
 if [[ ! $1 = "force" ]] && [[ ! $2 = "force" ]]; then
 	if [[ $* = "restore" ]] || [ ! -z $2 ]; then
@@ -126,10 +130,10 @@ if [[ ! $1 = "force" ]] && [[ ! $2 = "force" ]]; then
 		done
 	imageversion="$imagedir/imageversion"
 	[[ -f $imageversion ]] && cp -rf $imageversion $imageversion_local
-        [ ! -f $imagedir/$imagename ] && { printf '\n%s\n' "$imagedir/$imagename not found" && sleep 3 && clear && exit 1; }
-        [ ! -f $imagedir/$kernelname ] && { printf '\n%s\n' "$imagedir/$kernelname not found" && sleep 3 && clear && exit 1; }
+        [ ! -f $imagedir/$imagename ] && printf '\n%s\n' "$imagedir/$imagename not found" && exit_done
+        [ ! -f $imagedir/$kernelname ] && printf '\n%s\n' "$imagedir/$kernelname not found" && exit_done
         space_available="$(df -Pk $imagedir | awk 'NR==2 {print $4}')"
-        [ $space_available -lt 1048576 ] && { printf '\n\033[31m%s\n' "You need at least 1G of free space on your device" && sleep3 && clear && exit 1; }
+        [ $space_available -lt 1048576 ] && printf '\n\033[31m%s\n' "You need at least 1G of free space on your device" && exit_done
         write_image
 	fi
 fi
@@ -142,24 +146,24 @@ if [[ -z $1 ]] || [[ $* = "force" ]] || [[ ! $* = "restore" ]] || [[ $1 =~ ^[0-9
 			imageversion="$imagedir/imageversion"
 			[ ! -d $imagebase ] && mkdir -p $imagebase
 			space_available="$(df -Pk $imagebase | awk 'NR==2 {print $4}')"
-			[ $space_available -lt 1048576 ] && printf '\n\033[31m%s\n' "You need at least 1G of free space on $hdd_mount" && sleep 3 && clear && exit 3;
+			[ $space_available -lt 1048576 ] && printf '\n\033[31m%s\n' "You need at least 1G of free space on $hdd_mount" && exit_done
 			if [[ -z $2 ]] && [[ ! $1 = "force" ]]; then
         			[ ! -f $imageversion_local ] && touch $imageversion_local
 				md5_imageversion_online=$(curl -s $imageversion_online | md5sum | awk '{print $1}')
 				md5_imageversion_local=$(md5sum "$imageversion_local" | awk '{print $1}')
-				[ $md5_imageversion_online = $md5_imageversion_local ] && { printf '\n\033[32m%s\n\033[0m' "No update available" && \
-				echo "No update available" > $dev_display; sleep 3; clear; exit 4; }
+				[ $md5_imageversion_online = $md5_imageversion_local ] && printf '\n\033[32m%s\n\033[0m' "No update available" && \
+				echo "No update available" > $dev_display && exit_done;
 			elif [[ $1 = "force" ]] || [[ $2 = "force" ]]; then
                 		printf '\033[31m'
 			fi
 			echo "Downloading $image" > $dev_display
 			printf '\n\033[1m%s\n\033[0m' "Downloading $imagesource"
 			unpack="unzip -x $imagefile -d $imagebase"
-			curl $imagesource -o $imagefile || { printf '\n\033[31m%s\n' "Downloading the image failed"; sleep 3; clear; exit 5; }
+			curl $imagesource -o $imagefile || exit_done
 			[ -d $imagedir ] && rm -r $imagedir
 			echo "Decompressing $image" > $dev_display
         		printf '\n\033[1m%s\n\033[0m' "Decompressing  $image"
-			$unpack || { printf '\n\033[31m%s\n' "Unpacking the image failed" ; sleep 3; clear; exit 6; }
+			$unpack || exit_done;
 			[[ -f $imageversion ]] && cp -rf $imageversion $imageversion_local
 			[ -f $imagefile ] && rm $imagefile
 
