flash: try to be a little less sloppy

diff --git a/recipes-images/base-files/base-files/flash b/recipes-images/base-files/base-files/flash
--- a/recipes-images/base-files/base-files/flash
+++ b/recipes-images/base-files/base-files/flash
@@ -20,8 +20,8 @@ fi
 
 imagesource="https://tuxbox-images.de/images/hd51/neutrino-image_flash.zip"
 imagebase="/media/HDD/service/image"
+imagefile="$imagebase/hd51.zip"
 rootdevice="$(sed -e 's/^.*root=//' -e 's/ .*$//' < /proc/cmdline)"
-unzip="unzip -x hd51.zip"
 
 if  [ $1 -lt 1 ] || [ $1 -gt 4 ]; then
         printf '\n%s\n' "Choose a valid partition" && exit 1
@@ -32,31 +32,37 @@ reset && read -n1 -s -r -p "Press y to continue..." key
 if [ "$key" = 'y' ]; then
         reset
         if [ -z $2 ]; then
-                [ ! -e $imagebase ] && mkdir -p $imagebase
-                curl $imagesource -o $imagebase/hd51.zip
-                printf '\n%s\n'
-                rm -r $imagebase/hd51
-                cd $imagebase && $unzip
-                rm $imagebase/hd51.zip
                 imagedir="$imagebase/hd51"
+                unpack="unzip -x $imagefile -d $imagebase"
+                [ ! -e $imagebase ] && mkdir -p $imagebase
+                if [ -d $imagedir ]; then
+                        space_available="$(df -Pk $imagedir | awk 'NR==2 {print $4}')"
+                        if [ $space_available -lt 1048576 ];then
+                                printf '\n%s\n' "You need at least 1G of free space on your HDD" && exit 1
+                        fi
+                fi
+                curl $imagesource -o $imagefile || { printf '\n%s\n' "Downloading the image failed" ; exit 1; }
+                printf '\n%s\n'
+                [ -d $imagedir ] && rm -r $imagedir
+                $unpack || { printf '\n%s\n' "Unpacking the image failed" ; exit 1; }
+                [ -f $imagefile ] && rm $imagefile
         else
                 imagedir="$2"
+                space_available="$(df -Pk $imagedir | awk 'NR==2 {print $4}')"
                 if [ ! -f $imagedir/neutrino-image-hd51.ext4.bz2 ]; then
-                        printf '\n%s\n' "$2/neutrino-image-hd51.ext4.bz2 not found" && exit 1
+                                printf '\n%s\n' "$2/neutrino-image-hd51.ext4.bz2 not found" && exit 1
                 elif [ ! -f $imagedir/kernel.bin ]; then
                         printf '\n%s\n' "$2/kernel.bin not found" && exit 1
+                elif [ $space_available -lt 1048576 ];then
+                        printf '\n%s\n' "You need at least 1G of free space on your device" && exit 1
                 fi
         fi
 
-        dd_kernel="dd if=$imagedir/kernel.bin of=/dev/mmcblk0p$kernel bs=1M"
-        dd_rootfs="dd of=/dev/mmcblk0p$root bs=1M"
-        unpack="bzip2 -cd $imagedir/neutrino-image-hd51.ext4.bz2"
-
-        printf '\n%s\n' "Flashing Kernel into /dev/mmcblk0p$kernel"
-        $dd_kernel                      || { echo 'Flashing the kernel failed' ; exit 1; }
+        printf '\n%s\n' "Flashing kernel into /dev/mmcblk0p$kernel"
+        dd if=$imagedir/kernel.bin of=/dev/mmcblk0p$kernel bs=1M || { printf '\n%s\n' "Flashing the kernel failed" ; exit 1; }
 
         printf '\n%s\n' "Flashing rootfs into /dev/mmcblk0p$root"
-        $unpack | $dd_rootfs && sync    || { echo 'unpacking the rootfs failed' ; exit 1; }
+        bzip2 -cd $imagedir/neutrino-image-hd51.ext4.bz2 | dd of=/dev/mmcblk0p$root bs=1M && sync || { printf '\n%s\n' "Flash successful ... please unplug manually" ; exit 1; }
 
         if [ $rootdevice = /dev/mmcblk0p$root ]; then
                 printf '\n%s\n' "Flash successful"
@@ -67,4 +73,3 @@ if [ "$key" = 'y' ]; then
 else
         printf '\n%s\n' "Flashing image into partition_"$part" aborted" && exit 1
 fi
-
